const List = {
  user: {
    home: "/",
    login: "/login",
    register: "register",
    resetpassword: "resetpassword",
    about: "about",
    contact: "contact",
    HeaderNav: "navbar",
    cart: "cart",
    profile: "profile",
    orderList: "order-list",
  },
  admin: {
    admin: "/admin",
    login: "login",
    dashboard: "dashboard",
    categoryList: "categories",
    addCategory: "add-category",
    categoryDetails: "category-details",
    productList: "products",
    addProduct: "add-products",
    productDetails: "product-details",
    orderList: "orders",
    orderDetails: "order-details",
    stockList: "stocks",
    stockDetails: "stock-details",
    addStock: "add-stock",
    userList: "users",
    userDetails: "users-details",
    addUser: "add-user",
    homeManage: "home",
  },
};

export default List;
